name: safenotes_utils
description: Utilities for Safe Notes
homepage: https://safenotes.dev/
repository: https://github.com/keshav-space/safenotes-utils
version: 1.0.0

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
